[package]
name = "linux-keyutils-keyring"
version = "0.1.0"
edition = "2024"

[[example]]
name = "example"

[dependencies]
keyring = { version = "4.0.0-rc.1", default-features = false, path = "../keyring-rs" }
linux-keyutils = { version = "0.2.4", features = ["std"] }

[dev-dependencies]
fastrand = "2.3.0"
rpassword = "7.4.0"
