[package]
name = "linux-kernel-keystore"
version = "0.1.0"
edition = "2024"

[[example]]
name = "keystore"

[dependencies]
linux-keyutils = { version = "0.2.4", features = ["std"] }
keyring = { version = "4.0.0-rc.1", default-features = false }

[dev-dependencies]
fastrand = "2.3.0"
rpassword = "7.4.0"